package main.visitor;

import main.ast.nodes.Program;
import main.ast.nodes.Statement.*;
import main.ast.nodes.Statement.IterationStatement.*;
import main.ast.nodes.Statement.JumpStatement.*;
import main.ast.nodes.declaration.*;
import main.ast.nodes.expr.*;
import main.ast.nodes.expr.primitives.*;

public interface IVisitor<T> {
    T visit(Program program);
    T visit(ExternalDeclaration externalDeclaration);
    T visit(InitDeclarator initDeclarator);
    T visit(Declaration declaration);
    T visit(Declarator declarator);
    T visit(DirectDeclarator directDeclarator);
    T visit(Designator designator);
    T visit(Parameter parameter);
    T visit(Typename typename);
    T visit(Initializer initializer);
    T visit(InitializerList initializerList);
    T visit(Designation designation);
    T visit(BlockItem blockItem);
    T visit(CompoundStatement compoundStatement);
    T visit(ForStatement forStatement);
    T visit(WhileStatement whileStatement);
    T visit(DoWhileStatement doWhileStatement);
    T visit(ContinueStatement continueStatement);
    T visit(BreakStatement breakStatement);
    T visit(ReturnStatement returnStatement);
    T visit(ForCondition forCondition);
    T visit(ExpressionStatement expressionStatement);
    T visit(SelectionStatement selectionStatement);
    T visit(Pointer pointer);
    T visit(FunctionDefinition functionDefinition);
    T visit(UnaryExpr unaryExpr);
    T visit(BinaryExpr binaryExpr);
    T visit(Identifier identifier);
    T visit(StringExpr stringExpr);
    T visit(IniListExpr iniListExpr);
    T visit(ArrayExpr arrayExpr);
    T visit(CastExpr castExpr);
    T visit(FunctionExpr functionExpr);
    T visit(SizeofTypeExpr sizeofTypeExpr);
    T visit(TernaryExpr ternaryExpr);
    T visit(CommaExpr commaExpr);
    T visit(IntVal intVal);
    T visit(CharVal charVal);
    T visit(FloatVal floatVal);
}
